version: '3'

services:
  nats-server:
    image: nats:latest
    ports:
      - 8222:8222

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: client-gateway-prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    # volumes:
    #   - ./client-gateway/src:/usr/src/app/src
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  products-ms:
    build: 
     context: ./products-ms
     dockerfile: dockerfile.prod
    image: products-microservice
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  orders-ms:
    build: 
     context: ./orders-ms
     dockerfile: dockerfile.prod
     args: 
      - ORDERS_DATABASEURL=${ORDERS_DATABASEURL}
    image: orders-microservice
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DATABASEURL}

  # orders-db:
  #   container_name: orders_database
  #   image: postgres:16.2
  #   restart: always
  #   volumes:
  #     - ./orders-ms/postgres:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=123456
  #     - POSTGRES_DB=ordersdb

  payments-ms:
    build: 
     context: ./payments-ms
     dockerfile: dockerfile.prod
    volumes:
    - ./products-ms/database:/usr/src/app/database
    ports:
      - ${PAYMENTS_MICROSERVICE_PORT}:3004
    environment:
      - PORT=${PAYMENTS_MICROSERVICE_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINTSECRET=${STRIPE_ENDPOINTSECRET}

  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: auth-microservice
    environment:
      - PORT=3005
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
