apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
      - image: northamerica-south1-docker.pkg.dev/microservices-tienda-443601/image-registry/payments-ms
        name: payments-ms
        env:
        - name: PORT
          value: "3000"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: "STRIPE_SUCCESS_URL"
          value: "http://localhost:3004/payments/success"
        - name: "STRIPE_CANCEL_URL"
          value: "http://localhost:3004/payments/cancelled"
        - name: "STRIPE_ENDPOINTSECRET"
          valueFrom: 
            secretKeyRef:
              name: payments-secrets
              key: stripe_endpointsecret
        - name: "STRIPE_SECRET"
          valueFrom: 
            secretKeyRef:
              name: payments-secrets
              key: stripe_secret
        resources: {}
status: {}
